AWSTemplateFormatVersion: '2010-09-09'

###################################
Parameters:
  DSActivationKey:
    Default: ''
    Type: String
    Description: DataSync Activation Key
  
Resources:
  DSWSAgent:
    Type: AWS::DataSync::Agent
    Properties:
      ActivationKey: !Ref DSActivationKey
      AgentName: FsxWorkshopAgent
      SubnetArns:
        - !Sub ["arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet/${subnetid}", subnetid: !ImportValue "datasync-workshop-datasync-private-subnet"]
      SecurityGroupArns:
        - !Sub ["arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group/${sgid}", sgid: !ImportValue "datasync-workshop-datasync-vpcendpoint-security-group"]
      VpcEndpointId: !ImportValue "datasync-workshop-datasync-vpc-endpoint"
      Tags:
      - Key: Name
        Value: FsxWorkshopAgent
      - Key: OWner
        Value: FSX Workshop
      - Key: CostCenter
        Value: Datasync Migration Workshop

  SourceLocationSMB:
    Type: AWS::DataSync::LocationSMB
    Properties: 
      AgentArns: 
        - !Ref DSWSAgent
      MountOptions: 
        Version: SMB3

      # User: '{{resolve:secretsmanager:${secretName}:SecretString:username}}'
      # Password: '{{resolve:secretsmanager:${secretName}:SecretString:password}}'
      # Domain: '{{resolve:secretsmanager:${secretName}:SecretString:domain}}'
      User: '{{resolve:secretsmanager:DMSourceLocationUserSecret:SecretString:username}}'
      Password: '{{resolve:secretsmanager:DMSourceLocationUserSecret:SecretString:password}}'
      Domain: '{{resolve:secretsmanager:DMSourceLocationUserSecret:SecretString:domain}}'
      # Domain: !ImportValue "datasync-workshop-datasync-domain-name"

      ServerHostname: !ImportValue datasync-workshop-smb-windows-server-private-ip
      Subdirectory: '/share1'
      Tags: 
      - Key: Name
        Value: Source Location SMB Windows Server
      - Key: Owner
        Value: FSX Workshop
      - Key: CostCenter
        Value: Datasync Migration Workshop

  DestinationLocationFSxWindows:
    Type: AWS::DataSync::LocationFSxWindows
    Properties: 
      FsxFilesystemArn:  !ImportValue "datasync-workshop-fsx-arn"
      SecurityGroupArns: 
        - !Sub ["arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group/${sgid}", sgid: !ImportValue "datasync-workshop-location-fsx-windows-security-group"]
      Subdirectory: '/share1'
      
      User: '{{resolve:secretsmanager:DMSourceLocationUserSecret:SecretString:username}}'
      Password: '{{resolve:secretsmanager:DMSourceLocationUserSecret:SecretString:password}}'
      Domain: '{{resolve:secretsmanager:DMSourceLocationUserSecret:SecretString:domain}}'

      Tags: 
      - Key: Name
        Value: Destination Location FSX Windows
      - Key: Owner
        Value: FSX Workshop
      - Key: CostCenter
        Value: Datasync Migration Workshop

  WorkshopDataSyncLogs:
    Type: AWS::Logs::LogGroup
    # DeletionPolicy: Retain
    Properties:
      RetentionInDays: 7
      LogGroupName: !Join
        - ''
        - - DataSyncLogs-
          - !Ref 'AWS::StackName'
      Tags:
      - Key: Name
        Value: DMW-DataSyncLogs
      - Key: CostCenter
        Value: Datasync Migration Workshop

  WorkshopMigrationTask1:
    Type: AWS::DataSync::Task
    Properties: 
      Name: FSX Workshop Migration Task
      SourceLocationArn: !Ref SourceLocationSMB
      DestinationLocationArn: !Ref DestinationLocationFSxWindows
      CloudWatchLogGroupArn: !GetAtt WorkshopDataSyncLogs.Arn
      Options: 
        Atime: BEST_EFFORT
        # BytesPerSecond: Integer
        Gid: NONE
        LogLevel: TRANSFER
        Mtime: PRESERVE
        ObjectTags: PRESERVE
        # OverwriteMode: ALWAYS
        PosixPermissions: NONE
        PreserveDeletedFiles: PRESERVE
        PreserveDevices: NONE
        SecurityDescriptorCopyFlags: OWNER_DACL
        # TaskQueueing: ENABLED
        TransferMode: CHANGED
        Uid: NONE
        VerifyMode: ONLY_FILES_TRANSFERRED

      Schedule: 
        # cron expression https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions
        # cron(Minutes Hours Day-of-month Month Day-of-week Year)
        ScheduleExpression: cron(29 10 13 4 ? *)
        # ScheduleExpression: "at(2023-04-02T18:23:00)"
        # rate(<number>\s?(minutes?|hours?|days?)), cron(<cron_expression>) or at(yyyy-MM-dd'T'HH:mm:ss)
      Tags: 
      - Key: Name
        Value: Migration Task SMB to FSX
      - Key: Owner
        Value: FSX Workshop
      - Key: CostCenter
        Value: Datasync Migration Workshop
